import { Html, html } from 'foldkit/html'

import { Message, type TableOfContentsEntry } from '../../main'
import {
  bullets,
  infoCallout,
  inlineCode,
  link,
  pageTitle,
  para,
  tableOfContentsEntryToHeader,
  warningCallout,
} from '../../prose'
import {
  asyncDataRouter,
  bestPracticesImmutabilityRouter,
  comingFromTanStackQueryRouter,
  coreCommandsRouter,
  coreSubmodelRouter,
  coreUpdateRouter,
  patternsComposingUpdateStepsRouter,
  patternsModelAsCacheRouter,
  testingStoryRouter,
} from '../../route'
import * as Snippet from '../../snippet'
import { type CopiedSnippets, highlightedCodeBlock } from '../../view/codeBlock'

const overviewHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'overview',
  text: 'Overview',
}

const oneEntityManyCachesHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'one-entity-many-caches',
  text: 'One Entity, Many Caches',
}

const writeThroughHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'write-through-reflecting-the-change-everywhere',
  text: 'Write-Through: Reflecting the Change Everywhere',
}

const refreshableCapabilityRecordHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'the-refreshable-capability-record',
  text: 'The Refreshable Capability Record',
}

const revalidatingOnlyLoadedCachesHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'revalidating-only-loaded-caches',
  text: 'Revalidating Only Loaded Caches',
}

const composingInMutationHandlerHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'composing-it-in-a-mutation-handler',
  text: 'Composing It in a Mutation Handler',
}

const handlingAMoveHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'handling-a-move',
  text: 'Handling a Move',
}

const keepingStaleDataHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'keeping-stale-data-when-a-refresh-fails',
  text: 'Keeping Stale Data When a Refresh Fails',
}

const testingHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'testing',
  text: 'Testing',
}

export const tableOfContents: ReadonlyArray<TableOfContentsEntry> = [
  overviewHeader,
  oneEntityManyCachesHeader,
  writeThroughHeader,
  refreshableCapabilityRecordHeader,
  revalidatingOnlyLoadedCachesHeader,
  composingInMutationHandlerHeader,
  handlingAMoveHeader,
  keepingStaleDataHeader,
  testingHeader,
]

export const view = (copiedSnippets: CopiedSnippets): Html => {
  const h = html<Message>()

  return h.div(
    [],
    [
      pageTitle(
        'patterns/revalidating-caches',
        'Revalidating Caches After a Mutation',
      ),
      infoCallout(
        'Prerequisite',
        'This page builds on ',
        link(asyncDataRouter(), 'Async Data'),
        ', ',
        link(patternsModelAsCacheRouter(), 'The Model as Cache'),
        ', and ',
        link(patternsComposingUpdateStepsRouter(), 'Composing Update Steps'),
        '. Read those first if the six-state ',
        inlineCode('AsyncData'),
        ' type, the keyed ',
        inlineCode('HashMap'),
        ' caches, or the ',
        inlineCode('combine'),
        ' step composer are unfamiliar.',
      ),
      tableOfContentsEntryToHeader(overviewHeader),
      para(
        'A mutation succeeds on the server. Now the local Model has to agree with that new reality. There are two moves, and this page does both in order.',
      ),
      para(
        'First, write-through: reflect the change in the Model immediately, before any network round-trip. This is the optimistic update. The user sees their new Note appear the instant the create resolves, with no spinner and no flash of stale content.',
      ),
      para(
        'Second, reconcile: fire a background revalidation for every cache that could hold the mutated entity, so the local copy converges on whatever the server actually stored. The server may have set a timestamp, resolved a slug, or reordered a list, and the revalidation folds that authoritative version back in.',
      ),
      para(
        'If you have used TanStack Query, this is the same shape as an optimistic ',
        inlineCode('setQueryData'),
        ' followed by ',
        inlineCode('invalidateQueries'),
        '. The difference is that here there is no query cache hiding behind a hook. The caches are plain fields on your Model, the write-through is a pure Model-to-Model function, and the revalidation is a set of Commands returned from ',
        inlineCode('update'),
        '. Everything is data you can read, test, and diff.',
      ),
      infoCallout(
        'Independent moves',
        'Write-through and revalidation are independent. A handler can do only the optimistic write (nothing to reconcile), only the revalidation (a pull-to-refresh gesture with no local edit), or both (the common case). This page composes them, but they are separate tools.',
      ),
      tableOfContentsEntryToHeader(oneEntityManyCachesHeader),
      para(
        'The reason revalidation takes care is that one entity is not stored in one place. A single Note can be reachable through three different Model fields at once:',
      ),
      bullets(
        h.span(
          [],
          [inlineCode('allNotes'), ': the cross-notebook “All Notes” feed.'],
        ),
        h.span(
          [],
          [
            inlineCode('notesByNotebook'),
            ': a ',
            inlineCode('HashMap<NotebookId, AsyncData<...>>'),
            ' holding one Note list per Notebook.',
          ],
        ),
        h.span(
          [],
          [
            inlineCode('noteById'),
            ': a ',
            inlineCode('HashMap<NoteId, AsyncData<Note, NotesLoadError>>'),
            ' holding the single-Note detail view.',
          ],
        ),
      ),
      para(
        'When you edit a Note, its title might be showing in the All Notes feed, inside its Notebook’s list, and on its own detail page, all simultaneously, in three separately-loaded ',
        inlineCode('AsyncData'),
        ' values. A correct mutation handler has to touch every cache that currently holds the entity, and leave alone every cache that does not.',
      ),
      tableOfContentsEntryToHeader(writeThroughHeader),
      para(
        'Write-through is a pure function from Model to Model. It edits each relevant cache in place using ',
        inlineCode('AsyncData.map'),
        ', which transforms the ',
        inlineCode('data'),
        ' of every data-bearing state (',
        inlineCode('Success'),
        ', ',
        inlineCode('Refreshing'),
        ', ',
        inlineCode('Stale'),
        ') while preserving the tag, so a cache that is mid-refresh stays mid-refresh and simply carries the edited data forward.',
      ),
      para(
        'A create’s write-through prepends the new Note. Which cache it lands in depends on whether the Note belongs to a Notebook, so ',
        inlineCode('prependNewNote'),
        ' matches on ',
        inlineCode('maybeNotebookId'),
        ': no Notebook means it goes into the ',
        inlineCode('allNotes'),
        ' feed, a Notebook means it goes into that Notebook’s list in ',
        inlineCode('notesByNotebook'),
        '.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.revalidatingCachesPrependNewNoteHighlighted),
          ],
          [],
        ),
        Snippet.revalidatingCachesPrependNewNoteRaw,
        'Copy write-through create code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'An edit’s write-through replaces the Note wherever it appears. ',
        inlineCode('replaceNoteInCaches'),
        ' evolves all three fields at once. The feed and the detail entry always get the new version. The per-Notebook list only gets touched when the Note has a Notebook, so ',
        inlineCode('Option.match'),
        ' supplies ',
        inlineCode('identity'),
        ' for the ',
        inlineCode('onNone'),
        ' case, which leaves ',
        inlineCode('notesByNotebook'),
        ' exactly as it was.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(
              Snippet.revalidatingCachesReplaceNoteInCachesHighlighted,
            ),
          ],
          [],
        ),
        Snippet.revalidatingCachesReplaceNoteInCachesRaw,
        'Copy write-through edit code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'Two details are worth calling out. The ',
        inlineCode('noteById'),
        ' detail entry is set to ',
        inlineCode('AsyncData.Success'),
        ' outright, because after a successful edit we hold the authoritative Note and can promote the detail cache to fresh. The ',
        inlineCode('allNotes'),
        ' and per-Notebook lists use ',
        inlineCode('AsyncData.map'),
        ' instead, because we do not want to disturb their loaded-or-not state: if a list was never loaded, ',
        inlineCode('map'),
        ' is a no-op on ',
        inlineCode('Idle'),
        ', and nothing gets conjured into existence.',
      ),
      para(
        'This whole step is synchronous. No Command runs. The Model is already correct for the user before the server is asked to confirm anything.',
      ),
      tableOfContentsEntryToHeader(refreshableCapabilityRecordHeader),
      para(
        'Revalidation is uniform across every cache, so it ships as one combinator, ',
        inlineCode('Update.refresh'),
        ', rather than being repeated per field. The unit it returns is a ',
        inlineCode('Refresher'),
        ': an update step from Model to the standard ',
        inlineCode('[Model, Commands]'),
        ' return. Each concrete refresher is built by describing one cache as an ',
        inlineCode('Update.Refreshable'),
        ': how to read it, how to decide whether it needs revalidating, how to write the in-flight state back, and which Command reloads it.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.revalidatingCachesRefreshHighlighted),
          ],
          [],
        ),
        Snippet.revalidatingCachesRefreshRaw,
        'Copy refresher alias code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para('The record names four capabilities:'),
      bullets(
        h.span(
          [],
          [
            inlineCode('read'),
            ' gets the field’s AsyncData out of the Model. It returns an ',
            inlineCode('Option'),
            ' because keyed caches can miss (',
            inlineCode('HashMap.get'),
            '); single fields wrap in ',
            inlineCode('Option.some'),
            '.',
          ],
        ),
        h.span(
          [],
          [
            inlineCode('revalidate'),
            ' decides whether and how the entry transitions.',
          ],
        ),
        h.span(
          [],
          [
            inlineCode('write'),
            ' puts the transitioned entry back into the Model.',
          ],
        ),
        h.span(
          [],
          [inlineCode('load'), ' is the Command that refetches the data.'],
        ),
      ),
      para(
        inlineCode('Update.refresh'),
        ' turns the record into a step: it reads the current cache value, asks ',
        inlineCode('revalidate'),
        ' whether it should transition, and only when it says yes does it write the ',
        inlineCode('Refreshing'),
        ' state and emit the reload Command. When ',
        inlineCode('revalidate'),
        ' returns ',
        inlineCode('None'),
        ', the step is ',
        inlineCode('Update.noOp'),
        ': same Model, no Command. The ',
        inlineCode('revalidate'),
        ' field is exactly the free ',
        inlineCode('AsyncData.revalidate'),
        ' function; the ',
        inlineCode('Refreshable'),
        ' just names the four capabilities the combinator needs.',
      ),
      tableOfContentsEntryToHeader(revalidatingOnlyLoadedCachesHeader),
      para(
        'Here is the crux of the whole pattern. ',
        inlineCode('AsyncData.revalidate'),
        ' returns ',
        inlineCode('Some(Refreshing({ data }))'),
        ' for the two states that already hold data (',
        inlineCode('Success'),
        ' and ',
        inlineCode('Stale'),
        '), and ',
        inlineCode('None'),
        ' for every other state (',
        inlineCode('Idle'),
        ', ',
        inlineCode('Loading'),
        ', ',
        inlineCode('Refreshing'),
        ', ',
        inlineCode('Failure'),
        ').',
      ),
      para(
        'That single rule is what makes blanket revalidation safe. When a mutation handler fires a refresher at every cache that might hold the entity, only the caches that are actually loaded transition to ',
        inlineCode('Refreshing'),
        ' and reload. A cache sitting at ',
        inlineCode('Idle'),
        ', because that screen was never visited this session, yields ',
        inlineCode('None'),
        ' and stays ',
        inlineCode('Idle'),
        '. You do not accidentally fetch a Notebook’s Note list just because someone edited a Note in a different Notebook. The cache decides for itself whether it has anything to revalidate. (When a cache should load on entry instead, pass ',
        inlineCode('AsyncData.revalidateOrLoad'),
        ' as the ',
        inlineCode('revalidate'),
        ' capability: a cold cache then starts a first load rather than staying put.)',
      ),
      para('A refresher over a plain Model field reads it directly:'),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.revalidatingCachesFieldRefreshersHighlighted),
          ],
          [],
        ),
        Snippet.revalidatingCachesFieldRefreshersRaw,
        'Copy field refresher code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'A refresher over a keyed cache reads one entry out of the ',
        inlineCode('HashMap'),
        '. ',
        inlineCode('HashMap.get'),
        ' returns ',
        inlineCode('Option.none()'),
        ' when the key is absent, and ',
        inlineCode('Update.refresh'),
        ' treats a missing entry the same as a non-loaded one: nothing to revalidate. The public ',
        inlineCode('refreshNotebookNotes'),
        ' takes an ',
        inlineCode('Option<NotebookId>'),
        ', so a caller can pass a Note’s ',
        inlineCode('maybeNotebookId'),
        ' straight through; ',
        inlineCode('None'),
        ' means the Note has no Notebook and there is no per-Notebook list to touch.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.revalidatingCachesKeyedRefreshersHighlighted),
          ],
          [],
        ),
        Snippet.revalidatingCachesKeyedRefreshersRaw,
        'Copy keyed refresher code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'The single-Note detail refresher follows the same keyed shape over ',
        inlineCode('noteById'),
        ':',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.revalidatingCachesNoteRefresherHighlighted),
          ],
          [],
        ),
        Snippet.revalidatingCachesNoteRefresherRaw,
        'Copy detail refresher code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      tableOfContentsEntryToHeader(composingInMutationHandlerHeader),
      para(
        'A mutation handler does write-through first, then combines the refreshers. The write-through is piped into the Model, and ',
        inlineCode('Update.combine'),
        ' threads that Model through each refresher in turn, accumulating their Commands. A create is the simple case: reflect the new Note, then revalidate the feed and the Note’s Notebook list, and toast.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.revalidatingCachesCreateHandlerHighlighted),
          ],
          [],
        ),
        Snippet.revalidatingCachesCreateHandlerRaw,
        'Copy create handler code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'Each refresher in the list independently checks whether its cache is loaded and contributes a reload Command only if so. The ',
        inlineCode('showToast'),
        ' step is just another Model-to-',
        inlineCode('[Model, Commands]'),
        ' function in the same list, which is why it composes without special handling.',
      ),
      tableOfContentsEntryToHeader(handlingAMoveHeader),
      warningCallout(
        'Moves touch two Notebooks',
        'An edit can move a Note to a different Notebook. When it does, revalidating only the destination Notebook is a bug: the Notebook the Note left still shows it in its cached list. You have to revalidate both the Notebook joined and the Notebook left, and you must read the previous Notebook out of the cache before the write-through overwrites it.',
      ),
      para(
        'The edit handler receives the ',
        inlineCode('UpdatedNote'),
        ' OutMessage from the edit dialog. It captures ',
        inlineCode('previousNotebookId'),
        ' from ',
        inlineCode('noteById'),
        ' first, compares it against the incoming ',
        inlineCode('maybeNotebookId'),
        ' to decide whether the Note moved, then does the write-through and the refreshers. The moved case appends one extra refresher for the Notebook the Note left.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.revalidatingCachesEditHandlerHighlighted),
          ],
          [],
        ),
        Snippet.revalidatingCachesEditHandlerRaw,
        'Copy edit handler code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        inlineCode('noteNotebookId'),
        ' reads the previous Notebook by chaining through the detail cache. It only sees a Notebook if the Note’s detail is loaded and holds data, which is exactly when the previous per-Notebook list could be cached and therefore worth revalidating.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.revalidatingCachesNoteNotebookIdHighlighted),
          ],
          [],
        ),
        Snippet.revalidatingCachesNoteNotebookIdRaw,
        'Copy previous Notebook lookup code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'Because both ',
        inlineCode('refreshNotebookNotes(note.maybeNotebookId)'),
        ' and ',
        inlineCode('refreshNotebookNotes(previousNotebookId)'),
        ' funnel through ',
        inlineCode('AsyncData.revalidate'),
        ', an unloaded source or destination list is silently skipped. You always ask for both; only the loaded ones actually reload.',
      ),
      tableOfContentsEntryToHeader(keepingStaleDataHeader),
      para(
        'The revalidation fetches can fail. A background reload is exactly where you least want the screen to blank out, because the user already sees good data. This is the payoff of the sixth ',
        inlineCode('AsyncData'),
        ' state, and it is why ',
        inlineCode('Stale'),
        ' exists.',
      ),
      para(
        'The reload Command wraps its fetch in ',
        inlineCode('Effect.result'),
        ', so the ',
        inlineCode('Settled*'),
        ' Message carries a settled ',
        inlineCode('Result'),
        '. When it arrives, fold it into the previous cache value with ',
        inlineCode('AsyncData.settle'),
        '. On success it produces ',
        inlineCode('Success({ data })'),
        '. On failure it inspects the previous state: if that state held data (a ',
        inlineCode('Refreshing'),
        ' mid-reload always does), it produces ',
        inlineCode('Stale({ error, data })'),
        ', keeping the last-good data on screen alongside the error, rather than dropping to a bare ',
        inlineCode('Failure'),
        ' that would erase the list.',
      ),
      para(
        'The hand-written pair form looks like this: one handler sets the cache to fresh, its sibling sets it to ',
        inlineCode('Failure'),
        ' and throws away whatever was there.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.revalidatingCachesHandWrittenPairHighlighted),
          ],
          [],
        ),
        Snippet.revalidatingCachesHandWrittenPairRaw,
        'Copy hand-written pair code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'Both halves collapse into a single settled handler. The Message carries the ',
        inlineCode('Result'),
        ', so ',
        inlineCode('settle'),
        ' reads the previous state and decides between ',
        inlineCode('Success'),
        ' and ',
        inlineCode('Stale'),
        ':',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(
              Snippet.revalidatingCachesSettledLoadAllNotesHighlighted,
            ),
          ],
          [],
        ),
        Snippet.revalidatingCachesSettledLoadAllNotesRaw,
        'Copy settled handler code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'The keyed caches collapse the same way. ',
        inlineCode('HashMap.modify'),
        ' hands the previous entry to ',
        inlineCode('settle'),
        ', so when the reload of one Notebook’s list fails, that list stays visible as ',
        inlineCode('Stale'),
        ' while surfacing the error:',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.revalidatingCachesSettledLoadNotesHighlighted),
          ],
          [],
        ),
        Snippet.revalidatingCachesSettledLoadNotesRaw,
        'Copy keyed settled handler code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'Now the mutation flow is complete and resilient end to end: the write-through reflects the edit instantly, the refreshers reload only the loaded caches, and a failed reload settles to ',
        inlineCode('Stale'),
        ' instead of wiping the screen. See ',
        link(asyncDataRouter(), 'Async Data'),
        ' for the full ',
        inlineCode('settle'),
        ' semantics and the ',
        inlineCode('Stale'),
        ' state.',
      ),
      infoCallout(
        'First loads',
        inlineCode('settle'),
        ' keeps stale data only when the previous state had data. A first load that fails from ',
        inlineCode('Loading'),
        ' has nothing to keep, so it becomes ',
        inlineCode('Failure'),
        ', which is correct: there is no last-good list to preserve.',
      ),
      tableOfContentsEntryToHeader(testingHeader),
      para(
        'Because write-through, refreshers, and settling are all plain data transitions, a Story test can assert the exact cache states at each step. This test drives the move edit, checks that the affected caches flip to ',
        inlineCode('Refreshing'),
        ' synchronously, then resolves the two reloads.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.revalidatingCachesStoryTestHighlighted),
          ],
          [],
        ),
        Snippet.revalidatingCachesStoryTestRaw,
        'Copy Story test code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'The first ',
        inlineCode('Story.model'),
        ' assertion runs right after the mutation Message, before any Command resolves, so it captures the optimistic write plus the ',
        inlineCode('Refreshing'),
        ' transition in one snapshot. The keyed ',
        inlineCode('notesByNotebook'),
        ' entry and the ',
        inlineCode('noteById'),
        ' detail both read ',
        inlineCode('Refreshing'),
        ', holding their previous data while the reloads are in flight. The two ',
        inlineCode('Story.Command.resolve'),
        ' steps then settle those reloads, driving the caches to their final state. See ',
        link(testingStoryRouter(), 'Story'),
        ' for the Story harness.',
      ),
      para(
        'The pieces this page composes each have their own reference. ',
        link(asyncDataRouter(), 'Async Data'),
        ' covers the six-state type, the ',
        inlineCode('settle'),
        ' helper, and the ',
        inlineCode('Stale'),
        ' state. ',
        link(patternsModelAsCacheRouter(), 'The Model as Cache'),
        ' covers the ',
        inlineCode('HashMap'),
        ' cache fields and their ',
        inlineCode('AsyncData'),
        ' entries, and ',
        link(patternsComposingUpdateStepsRouter(), 'Composing Update Steps'),
        ' covers the ',
        inlineCode('combine'),
        ' step composer used to thread the refreshers. The ',
        inlineCode('[Model, Commands]'),
        ' return the mutation handlers produce is described in ',
        link(coreUpdateRouter(), 'Update'),
        ', and the ',
        inlineCode('Load*'),
        ' Commands the refreshers emit are ordinary Commands, described in ',
        link(coreCommandsRouter(), 'Commands'),
        '; the settled ',
        inlineCode('Result'),
        ' each one carries back in its Message is covered on ',
        link(asyncDataRouter(), 'Async Data'),
        '.',
      ),
      para(
        'The mutation itself arrives as an OutMessage the parent forwards, which the ',
        link(coreSubmodelRouter(), 'Submodel'),
        ' page covers. ',
        link(comingFromTanStackQueryRouter(), 'Coming from TanStack Query'),
        ' maps write-through to ',
        inlineCode('setQueryData'),
        ' and revalidation to ',
        inlineCode('invalidateQueries'),
        ', and ',
        link(bestPracticesImmutabilityRouter(), 'Immutability'),
        ' explains why write-through is a pure Model-to-Model transform.',
      ),
    ],
  )
}
