import { Html, html } from 'foldkit/html'

import { Message, type TableOfContentsEntry } from '../../main'
import {
  infoCallout,
  inlineCode,
  link,
  pageTitle,
  para,
  tableOfContentsEntryToHeader,
} from '../../prose'
import {
  asyncDataRouter,
  comingFromTanStackQueryRouter,
  coreCommandsRouter,
  coreUpdateRouter,
  exampleDetailRouter,
  patternsInformingSubmodelsRouter,
  patternsModelAsCacheRouter,
  patternsRevalidatingCachesRouter,
  routingAndNavigationRouter,
} from '../../route'
import * as Snippet from '../../snippet'
import { type CopiedSnippets, highlightedCodeBlock } from '../../view/codeBlock'

const overviewHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'overview',
  text: 'Overview',
}

const routeTransitionHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'the-route-transition',
  text: 'The Route Transition',
}

const loadingPoliciesHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'load-if-missing-vs-revalidate-on-entry',
  text: 'Load If Missing vs Revalidate on Entry',
}

const stepFunctionHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'writing-a-step-function',
  text: 'Writing a Step Function',
}

const genuineEntryHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'genuine-entry-vs-in-place-update',
  text: 'Genuine Entry vs In-Place Update',
}

const entryPointsHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'one-policy-two-entry-points',
  text: 'One Policy, Two Entry Points',
}

export const tableOfContents: ReadonlyArray<TableOfContentsEntry> = [
  overviewHeader,
  routeTransitionHeader,
  loadingPoliciesHeader,
  stepFunctionHeader,
  genuineEntryHeader,
  entryPointsHeader,
]

export const view = (copiedSnippets: CopiedSnippets): Html => {
  const h = html<Message>()

  return h.div(
    [],
    [
      pageTitle('patterns/route-driven-loading', 'Route-Driven Loading'),
      infoCallout(
        'Prerequisite',
        'This page builds on ',
        link(asyncDataRouter(), 'Async Data'),
        ' (the ',
        inlineCode('AsyncData'),
        ' value type, ',
        inlineCode('AsyncData.revalidateOrLoad'),
        ', and ',
        inlineCode('AsyncData.revalidate'),
        ') and on ',
        link(
          `${routingAndNavigationRouter()}#cold-loads`,
          'Routing & Navigation (Cold Loads)',
        ),
        ', which covers how ',
        inlineCode('init'),
        ' parses the initial URL. Read those first.',
      ),
      para(
        'Loading is not an event you fire from a click handler. It is a function of the URL. This page shows how to compute, on every route change, which caches a screen needs and whether each one should fetch, then run that same computation once more at boot so a cold load and a navigation share one policy.',
      ),
      tableOfContentsEntryToHeader(overviewHeader),
      para(
        'A screen renders from cache fields on the Model: a list of notebooks, one notebook’s notes, a single note. Someone has to decide when those fields fetch. Wiring a fetch into each link or button scatters that decision across the view and invites two failure modes: navigating to a screen you already loaded refetches it (a flash of a spinner over data you were just looking at), and navigating away and back blanks the screen while it reloads.',
      ),
      para(
        'The route already knows what a screen needs. So the loading policy is a pure function of the route transition: given the route we came from and the route we are going to, decide per cache whether to fetch and what next Command to issue. Each cache gets one small step function. On a route change, update runs every step function, collects the next cache values into the Model, and concatenates the Commands. Because the decision is centralized and derived, it can be precise: never double-fetch on navigation, never blank a screen that already holds data.',
      ),
      tableOfContentsEntryToHeader(routeTransitionHeader),
      para(
        'Every step function takes the same input: a ',
        inlineCode('RouteTransition'),
        '. It carries the route we are leaving as an ',
        inlineCode('Option'),
        ' and the route we are entering. The type and its entry predicate ship in foldkit; the application pins its route union once and aliases both.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.routeDrivenLoadingRouteTransitionHighlighted),
          ],
          [],
        ),
        Snippet.routeDrivenLoadingRouteTransitionRaw,
        'Copy route transition code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        inlineCode('isTransitionTo(tag)'),
        ' is true when we are arriving at ',
        inlineCode('tag'),
        ' from somewhere else. If ',
        inlineCode('previousRoute'),
        ' is ',
        inlineCode('None'),
        ' (a cold load), any destination counts as an arrival. If it is ',
        inlineCode('Some'),
        ', we only count it as an arrival when the previous tag differs, so moving between two ',
        inlineCode('NoteViewer'),
        ' routes is not “entering the viewer”.',
      ),
      para(
        'Making ',
        inlineCode('previousRoute'),
        ' an ',
        inlineCode('Option'),
        ' rather than a plain ',
        inlineCode('Route'),
        ' is the choice the pattern rests on. It is what lets ',
        inlineCode('init'),
        ' reuse these exact step functions: at boot there is no previous route, so ',
        inlineCode('init'),
        ' passes ',
        inlineCode('Option.none()'),
        ' and every ',
        inlineCode('isTransitionTo'),
        ' check reads as a genuine entry. One transition shape serves both entry points.',
      ),
      tableOfContentsEntryToHeader(loadingPoliciesHeader),
      para(
        'There are two loading policies, and you pick one per cache per destination.',
      ),
      para(
        'Revalidate on entry: the screen that owns a cache needs fresh data each time you arrive, but should keep showing the last-good data while the refetch runs. This is stale-while-revalidate. The ',
        inlineCode('NotebooksList'),
        ' route revalidates the notebooks cache; the ',
        inlineCode('AllNotes'),
        ' route revalidates the cross-notebook feed.',
      ),
      para(
        'Load if missing: a screen needs a cache present but does not care that it is fresh. Fetch it once when it is absent, then leave it alone. A ',
        inlineCode('NoteViewer'),
        ' needs the notebooks list only for the edit dialog’s notebook picker, so it loads notebooks when missing rather than refetching them on every note view.',
      ),
      para(
        'You do not hand-write either policy. ',
        inlineCode('AsyncData.revalidateOrLoad'),
        ' encodes the revalidate decision, freshness and dedupe included: a loaded ',
        inlineCode('Success'),
        ' or ',
        inlineCode('Stale'),
        ' becomes ',
        inlineCode('Refreshing'),
        ' (keep the data, fetch again), a cold ',
        inlineCode('Idle'),
        ' or ',
        inlineCode('Failure'),
        ' becomes ',
        inlineCode('Loading'),
        ' (no data to keep, fetch fresh), and an already in-flight ',
        inlineCode('Loading'),
        ' or ',
        inlineCode('Refreshing'),
        ' yields ',
        inlineCode('None'),
        ' so a second entry does not restart a live request. ',
        inlineCode('None'),
        ' means “no transition needed, issue no Command”. Load-if-missing is just as small: gate on ',
        inlineCode('AsyncData.hasData'),
        ', and when it is absent set ',
        inlineCode('Loading'),
        ' and fetch.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.routeDrivenLoadingPolicyHelpersHighlighted),
          ],
          [],
        ),
        Snippet.routeDrivenLoadingPolicyHelpersRaw,
        'Copy loading policy code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      infoCallout(
        'None means do nothing',
        'Both helpers return ',
        inlineCode('Option<[nextValue, Commands]>'),
        '. ',
        inlineCode('None'),
        ' is the “do nothing” case: keep the cache as it is and issue no Command. The step function turns that ',
        inlineCode('None'),
        ' back into the unchanged cache. See ',
        link(asyncDataRouter(), 'Async Data'),
        ' for the full state-by-state table behind ',
        inlineCode('AsyncData.revalidateOrLoad'),
        ' and ',
        inlineCode('AsyncData.revalidate'),
        '.',
      ),
      tableOfContentsEntryToHeader(stepFunctionHeader),
      para(
        'A step function is the whole policy for one cache: read the destination, decide, and return the next cache value plus any Commands. Here is the keyed note cache, ',
        inlineCode('stepNoteById'),
        ', which is load-if-missing over a ',
        inlineCode('HashMap<NoteId, AsyncData<Note, NotesLoadError>>'),
        '.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.routeDrivenLoadingStepNoteByIdHighlighted),
          ],
          [],
        ),
        Snippet.routeDrivenLoadingStepNoteByIdRaw,
        'Copy step function code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        inlineCode('routeToMaybeViewerNoteId'),
        ' returns ',
        inlineCode('Some(noteId)'),
        ' only on the ',
        inlineCode('NoteViewer'),
        ' route and ',
        inlineCode('None'),
        ' everywhere else, so ',
        inlineCode('stepNoteById'),
        ' is inert on every other screen. When we do enter the viewer, ',
        inlineCode('loadNote'),
        ' checks the cache: if that note already has data, ',
        inlineCode('liftPredicate'),
        ' fails and the whole chain collapses to ',
        inlineCode('None'),
        '. The final ',
        inlineCode('getOrElse'),
        ' turns any ',
        inlineCode('None'),
        ' into the unchanged cache with no Command. Returning to a note you already loaded therefore fetches nothing, which is what makes back-navigation instant. Only a genuinely missing note gets a ',
        inlineCode('Loading'),
        ' entry and a ',
        inlineCode('LoadNote'),
        ' Command.',
      ),
      para(
        'Every step function has this shape: pull the relevant key or flag off ',
        inlineCode('nextRoute'),
        ', run a policy that yields ',
        inlineCode('Option<[nextCache, Commands]>'),
        ', and ',
        inlineCode('getOrElse'),
        ' to the untouched cache. The route decides relevance; ',
        inlineCode('AsyncData'),
        ' decides the fetch.',
      ),
      tableOfContentsEntryToHeader(genuineEntryHeader),
      para(
        'Some routes carry state that changes without the route tag changing. The ',
        inlineCode('AllNotes'),
        ' feed has a filter. Tweaking that filter keeps you on ',
        inlineCode('AllNotes'),
        ' but changes the URL, so ',
        inlineCode('handleChangedUrl'),
        ' runs again. You do not want the feed to refetch on a filter change. This is exactly what ',
        inlineCode('isTransitionTo'),
        ' guards.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.routeDrivenLoadingStepAllNotesHighlighted),
          ],
          [],
        ),
        Snippet.routeDrivenLoadingStepAllNotesRaw,
        'Copy genuine entry step code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        inlineCode('stepAllNotes'),
        ' only revalidates when the transition is a genuine entry into ',
        inlineCode('AllNotes'),
        '. Arrive from another route and it refreshes; change the filter while already on ',
        inlineCode('AllNotes'),
        ' and ',
        inlineCode('isTransitionTo'),
        ' is false, so the step is inert and the feed is untouched. The same handler updates other Model fields in response to the filter change, but it does not disturb the cache.',
      ),
      para(
        'The other axis is policy per cache per destination. The same cache can call for different behavior on different routes. The notebooks cache revalidates on its own list route but only loads-if-missing on the viewer route, so its step function branches on the destination tag.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.routeDrivenLoadingStepNotebooksHighlighted),
          ],
          [],
        ),
        Snippet.routeDrivenLoadingStepNotebooksRaw,
        'Copy per-destination step code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'On ',
        inlineCode('NotebooksList'),
        ' the cache revalidates; on ',
        inlineCode('NoteViewer'),
        ' it loads only if missing; on any other route it does nothing. One cache, one step function, a policy chosen by where you are going.',
      ),
      tableOfContentsEntryToHeader(entryPointsHeader),
      para(
        'Loading starts in response to two events: the app boots, and the URL changes. Both come down to a ',
        inlineCode('RouteTransition'),
        ' and the same set of step functions. The only difference is ',
        inlineCode('previousRoute'),
        '.',
      ),
      para(
        'At boot, ',
        inlineCode('init'),
        ' has no previous route, so it passes ',
        inlineCode('Option.none()'),
        ' and seeds each cache with its empty starting value (',
        inlineCode('AsyncData.Idle()'),
        ' for a single value, ',
        inlineCode('HashMap.empty()'),
        ' for a keyed cache).',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.routeDrivenLoadingInitHighlighted),
          ],
          [],
        ),
        Snippet.routeDrivenLoadingInitRaw,
        'Copy init code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'On navigation, ',
        inlineCode('handleChangedUrl'),
        ' has a real previous route (',
        inlineCode('model.route'),
        ') and reads each cache off the current Model instead of an empty seed. Otherwise it is the identical call set, feeding the same step functions.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.routeDrivenLoadingHandleChangedUrlHighlighted),
          ],
          [],
        ),
        Snippet.routeDrivenLoadingHandleChangedUrlRaw,
        'Copy handleChangedUrl code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'Because ',
        inlineCode('previousRoute'),
        ' is an ',
        inlineCode('Option'),
        ', ',
        inlineCode('isTransitionTo'),
        ' treats the cold load as a genuine entry into whatever route the URL resolves to, so a deep link to ',
        inlineCode('NoteViewer'),
        ' fetches exactly the caches that screen needs, no more. The boot path and the navigation path never drift, because there is only one policy. The two entry points just supply it a different ',
        inlineCode('previousRoute'),
        '.',
      ),
      infoCallout(
        'Refreshing after mutations',
        'This page covers loading on route entry. The complementary pattern is refreshing a cache after a mutation without a route change, which reuses ',
        inlineCode('AsyncData.revalidate'),
        ' through ',
        inlineCode('Update.refresh'),
        '. See ',
        link(coreCommandsRouter(), 'Commands'),
        ' and the ',
        link(patternsRevalidatingCachesRouter(), 'refresher pattern'),
        ' for that side.',
      ),
      para(
        'The ',
        link(exampleDetailRouter({ exampleSlug: 'api-cache' }), 'api-cache'),
        ' example makes the same decisions from tab activation instead of route entry: a keyed ',
        inlineCode('HashMap'),
        ' cache, ',
        inlineCode('revalidateOrLoad'),
        ' when a tab opens, and ',
        inlineCode('settle'),
        ' when the fetch completes. ',
        link(patternsModelAsCacheRouter(), 'The Model as Cache'),
        ' covers how the notebooks, notebookById, allNotes, notesByNotebook, and noteById fields are shaped on the Model, and ',
        link(asyncDataRouter(), 'Async Data'),
        ' has the full behavior of ',
        inlineCode('AsyncData.revalidateOrLoad'),
        ', ',
        inlineCode('AsyncData.revalidate'),
        ', ',
        inlineCode('hasData'),
        ', and ',
        inlineCode('getData'),
        '.',
      ),
      para(
        'The ',
        link(coreUpdateRouter(), 'Update'),
        ' guide covers how ',
        inlineCode('handleChangedUrl'),
        ' sits inside the top-level update and batches every cache’s Commands, and ',
        link(coreCommandsRouter(), 'Commands'),
        ' covers the ',
        inlineCode('LoadNotebooks'),
        ' and ',
        inlineCode('LoadNote'),
        ' Commands these step functions return and how their results settle back into the caches. ',
        link(patternsInformingSubmodelsRouter(), 'Informing Submodels'),
        ' is the sibling pattern for handing a route change to a Submodel that owns other state, and ',
        link(comingFromTanStackQueryRouter(), 'Coming from TanStack Query'),
        ' contrasts route-driven loading with a query cache’s automatic fetching.',
      ),
    ],
  )
}
