import { Schema as S } from 'effect'
import { defineMessageUnion } from 'foldkit/message'

import {
  Animation,
  Calendar,
  Combobox,
  DatePicker,
  Dialog,
  DragAndDrop,
  FileDrop,
  Listbox,
  Menu,
  Popover,
  RadioGroup,
  Slider,
  Tabs,
  Tooltip,
  VirtualList,
} from '@foldkit/ui'

import { Toast } from './toastModule'

export const Message = defineMessageUnion({
  ClickedButtonDemo: {},
  UpdatedInputDemoValue: { value: S.String },
  UpdatedTextareaDemoValue: { value: S.String },
  UpdatedFieldsetInputValue: { value: S.String },
  UpdatedFieldsetTextareaValue: { value: S.String },
  ToggledFieldsetCheckboxDemo: { isChecked: S.Boolean },
  GotCalendarBasicDemoMessage: { message: Calendar.Message },
  GotDatePickerBasicDemoMessage: { message: DatePicker.Message },
  ToggledCheckboxBasicDemo: { isChecked: S.Boolean },
  ToggledCheckboxAllDemo: { isChecked: S.Boolean },
  ToggledCheckboxOptionADemo: { isChecked: S.Boolean },
  ToggledCheckboxOptionBDemo: { isChecked: S.Boolean },
  GotComboboxDemoMessage: { message: Combobox.Message },
  GotComboboxPlacementLockDemoMessage: { message: Combobox.Message },
  GotComboboxNullableDemoMessage: { message: Combobox.Message },
  GotComboboxMultiDemoMessage: { message: Combobox.Message },
  GotComboboxSelectOnFocusDemoMessage: { message: Combobox.Message },
  GotDialogDemoMessage: { message: Dialog.Message },
  GotDialogAnimatedDemoMessage: { message: Dialog.Message },
  GotOverlayDialogDemoMessage: { message: Dialog.Message },
  GotOverlayComboboxDemoMessage: { message: Combobox.Message },
  GotNestedDialogParentDemoMessage: { message: Dialog.Message },
  GotNestedDialogChildDemoMessage: { message: Dialog.Message },
  ClickedDeleteProject: {},
  ClickedOpenDialog: {},
  ClickedOpenAnimatedDialog: {},
  ClickedEditFilters: {},
  ClickedOpenProjectSettings: {},
  ToggledDisclosureDemo: { isOpen: S.Boolean },
  GotListboxDemoMessage: { message: Listbox.Message },
  GotListboxMultiDemoMessage: { message: Listbox.Message },
  GotListboxGroupedDemoMessage: { message: Listbox.Message },
  GotMenuBasicDemoMessage: { message: Menu.Message },
  GotMenuAnimatedDemoMessage: { message: Menu.Message },
  GotPopoverBasicDemoMessage: { message: Popover.Message },
  GotPopoverAnimatedDemoMessage: { message: Popover.Message },
  GotPopoverArrowDemoMessage: { message: Popover.Message },
  GotPopoverNestedParentDemoMessage: { message: Popover.Message },
  GotPopoverNestedChildDemoMessage: { message: Popover.Message },
  GotVerticalRadioGroupDemoMessage: { message: RadioGroup.Message },
  GotHorizontalRadioGroupDemoMessage: { message: RadioGroup.Message },
  UpdatedSelectDemoValue: { value: S.String },
  GotSliderRatingDemoMessage: { message: Slider.Message },
  GotSliderVolumeDemoMessage: { message: Slider.Message },
  ToggledSwitchDemo: { isChecked: S.Boolean },
  GotHorizontalTabsDemoMessage: { message: Tabs.Message },
  GotVerticalTabsDemoMessage: { message: Tabs.Message },
  GotDragAndDropDemoMessage: { message: DragAndDrop.Message },
  GotFileDropBasicDemoMessage: { message: FileDrop.Message },
  ClickedRemoveFileDropDemoFile: { fileIndex: S.Number },
  GotToastDemoMessage: { message: Toast.Message },
  ClickedShowInfoToast: {},
  ClickedShowSuccessToast: {},
  ClickedShowErrorToast: {},
  ClickedShowStickyToast: {},
  ClickedDismissAllToasts: {},
  GotTooltipDemoMessage: { message: Tooltip.Message },
  GotAnimationDemoMessage: { message: Animation.Message },
  GotVirtualListDemoMessage: { message: VirtualList.Message },
  ClickedVirtualListScrollToMiddle: {},
  GotVirtualListVariableDemoMessage: { message: VirtualList.Message },
  ClickedVirtualListVariableScrollToMiddle: {},
})
export type Message = typeof Message.Type
